-- Keldon's RFTG server tables for SQLite.
-- The server creates these automatically when it opens the database file.

CREATE TABLE IF NOT EXISTS users(
 uid INTEGER PRIMARY KEY AUTOINCREMENT,
 user TEXT NOT NULL,
 pass TEXT NOT NULL);

CREATE INDEX IF NOT EXISTS users_user_idx ON users(user);

CREATE TABLE IF NOT EXISTS games(
 gid INTEGER PRIMARY KEY AUTOINCREMENT,
 description TEXT NOT NULL,
 pass TEXT NOT NULL,
 created INTEGER NOT NULL,
 state TEXT NOT NULL,
 minp INTEGER NOT NULL,
 maxp INTEGER NOT NULL,
 exp INTEGER NOT NULL,
 adv INTEGER NOT NULL,
 dis_goal INTEGER NOT NULL,
 dis_takeover INTEGER NOT NULL,
 speed INTEGER NOT NULL,
 version TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS attendance(
 uid INTEGER NOT NULL,
 gid INTEGER NOT NULL,
 ai INTEGER NOT NULL DEFAULT 0,
 seat INTEGER NOT NULL DEFAULT 0,
 waiting TEXT);

CREATE INDEX IF NOT EXISTS attendance_gid_seat_idx
 ON attendance(gid, seat);

CREATE TABLE IF NOT EXISTS results(
 gid INTEGER NOT NULL,
 uid INTEGER NOT NULL,
 vp INTEGER NOT NULL,
 tie INTEGER NOT NULL,
 winner INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS seed(
 gid INTEGER PRIMARY KEY,
 pool BLOB NOT NULL);

CREATE TABLE IF NOT EXISTS choices(
 gid INTEGER NOT NULL,
 uid INTEGER NOT NULL,
 log BLOB NOT NULL,
 PRIMARY KEY (gid, uid));

CREATE TABLE IF NOT EXISTS messages(
 mid INTEGER PRIMARY KEY AUTOINCREMENT,
 gid INTEGER NOT NULL,
 uid INTEGER NOT NULL,
 message TEXT NOT NULL,
 format TEXT NOT NULL DEFAULT '');
